In [98]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

**Customer or Account Details**

In [99]:
df_acc = pd.read_csv('ravenstack_accounts.csv')

In [100]:
df_acc.head(5)

,account_id,account_name,industry,country,signup_date,referral_source,plan_tier,seats,is_trial,churn_flag
0,A-2e4581,Company_0,EdTech,US,2024-10-16,partner,Basic,9,False,False
1,A-43a9e3,Company_1,FinTech,IN,2023-08-17,other,Basic,18,False,True
2,A-0a282f,Company_2,DevTools,US,2024-08-27,organic,Basic,1,False,False
3,A-1f0ac7,Company_3,HealthTech,UK,2023-08-27,other,Basic,24,True,False
4,A-ce550d,Company_4,HealthTech,US,2024-10-27,event,Enterprise,35,False,True

In [101]:
# Check distribution of churn flag
df_acc["churn_flag"].value_counts(dropna=False)

churn_flag
False    390
True     110
Name: count, dtype: int64

In [102]:
df_acc["churn_flag"].unique()

array([False,  True])

In [103]:
df_acc['signup_date'] = pd.to_datetime(df_acc['signup_date'].astype(str), format='%Y-%m-%d',errors='coerce')

In [104]:
df_acc.isnull()

,account_id,account_name,industry,country,signup_date,referral_source,plan_tier,seats,is_trial,churn_flag
0,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
495,False,False,False,False,False,False,False,False,False,False
496,False,False,False,False,False,False,False,False,False,False
497,False,False,False,False,False,False,False,False,False,False
498,False,False,False,False,False,False,False,False,False,False
499,False,False,False,False,False,False,False,False,False,False

In [105]:
df_acc.head()

,account_id,account_name,industry,country,signup_date,referral_source,plan_tier,seats,is_trial,churn_flag
0,A-2e4581,Company_0,EdTech,US,2024-10-16,partner,Basic,9,False,False
1,A-43a9e3,Company_1,FinTech,IN,2023-08-17,other,Basic,18,False,True
2,A-0a282f,Company_2,DevTools,US,2024-08-27,organic,Basic,1,False,False
3,A-1f0ac7,Company_3,HealthTech,UK,2023-08-27,other,Basic,24,True,False
4,A-ce550d,Company_4,HealthTech,US,2024-10-27,event,Enterprise,35,False,True

In [106]:
df_acc.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   account_id       500 non-null    object
 1   account_name     500 non-null    object
 2   industry         500 non-null    object
 3   country          500 non-null    object
 4   signup_date      500 non-null    datetime64[ns]
 5   referral_source  500 non-null    object
 6   plan_tier        500 non-null    object
 7   seats            500 non-null    int64
 8   is_trial         500 non-null    bool
 9   churn_flag       500 non-null    bool
dtypes: bool(2), datetime64[ns](1), int64(1), object(6)
memory usage: 32.4+ KB

In [107]:
df_acc[["account_id", "signup_date", "churn_flag"]].isna().sum()

account_id     0
signup_date    0
churn_flag     0
dtype: int64

**Churn Data**

In [108]:
df_churn=pd.read_csv('ravenstack_churn_events.csv')

In [109]:
df_churn.head(3)

,churn_event_id,account_id,churn_date,reason_code,refund_amount_usd,preceding_upgrade_flag,preceding_downgrade_flag,is_reactivation,feedback_text
0,C-816288,A-c37cab,2024-10-27,pricing,4.03,False,False,False,switched to competitor
1,C-5a81e7,A-37f969,2024-06-25,support,96.45,True,False,False,NaN
2,C-a174be,A-b07346,2024-11-12,budget,0.00,False,False,False,missing features

In [110]:
df_churn.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 600 entries, 0 to 599
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   churn_event_id            600 non-null    object
 1   account_id                600 non-null    object
 2   churn_date                600 non-null    object
 3   reason_code               600 non-null    object
 4   refund_amount_usd         600 non-null    float64
 5   preceding_upgrade_flag    600 non-null    bool
 6   preceding_downgrade_flag  600 non-null    bool
 7   is_reactivation           600 non-null    bool
 8   feedback_text             452 non-null    object
dtypes: bool(3), float64(1), object(5)
memory usage: 30.0+ KB

In [111]:
df_churn['churn_date'] = pd.to_datetime(df_churn['churn_date'].astype(str), format='%Y-%m-%d',errors='coerce')

In [112]:
df_churn[["account_id", "churn_date"]].isna().sum()

account_id    0
churn_date    0
dtype: int64

**Feature Usage**

In [113]:
df_ft_us=pd.read_csv('ravenstack_feature_usage.csv')

In [114]:
df_ft_us.head()

,usage_id,subscription_id,usage_date,feature_name,usage_count,usage_duration_secs,error_count,is_beta_feature
0,U-1c6c24,S-0fcf7d,2023-07-27,feature_20,9,5004,0,False
1,U-f07cb8,S-c25263,2023-08-07,feature_5,9,369,0,False
2,U-096807,S-f29e7f,2023-12-07,feature_3,9,1458,0,False
3,U-6b1580,S-be655e,2024-07-28,feature_40,5,2085,0,False
4,U-720a29,S-f9b1d0,2024-12-02,feature_12,12,900,0,False

In [115]:
df_ft_us['usage_date']=pd.to_datetime(df_ft_us['usage_date'].astype(str),format='%Y-%m-%d',errors='coerce')

**Subscriptions**

In [116]:
df_subs=pd.read_csv('ravenstack_subscriptions.csv')

In [117]:
df_subs

,subscription_id,account_id,start_date,end_date,plan_tier,seats,mrr_amount,arr_amount,is_trial,upgrade_flag,downgrade_flag,churn_flag,billing_frequency,auto_renew_flag
0,S-8cec59,A-3c1a3f,2023-12-23,2024-04-12,Enterprise,14,2786,33432,False,False,False,True,monthly,True
1,S-0f6f44,A-9b9fe9,2024-06-11,NaN,Pro,17,833,9996,False,False,False,False,monthly,True
2,S-51c0d1,A-659280,2024-11-25,NaN,Enterprise,62,0,0,True,True,False,False,annual,False
3,S-f81687,A-e7a1e2,2024-11-23,2024-12-13,Enterprise,5,995,11940,False,False,False,True,monthly,True
4,S-cff5a2,A-ba6516,2024-01-10,NaN,Enterprise,27,5373,64476,False,False,False,False,monthly,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,S-c158df,A-fa2041,2024-10-27,NaN,Enterprise,18,3582,42984,False,False,False,False,monthly,True
4996,S-b49c0a,A-db5e9e,2024-12-05,NaN,Pro,23,1127,13524,False,False,False,False,monthly,False
4997,S-42822d,A-443f6f,2024-12-15,NaN,Pro,25,1225,14700,False,False,False,False,annual,True
4998,S-432401,A-c7ffc2,2023-05-25,NaN,Pro,132,6468,77616,False,False,False,False,monthly,True
4999,S-71fc3d,A-ccb686,2024-12-06,NaN,Enterprise,10,1990,23880,False,False,False,False,monthly,True

In [118]:
df_subs['start_date'] = pd.to_datetime(df_subs['start_date'], format='%Y-%m-%d',errors='coerce')
df_subs['end_date'] = pd.to_datetime(df_subs['end_date'], format='%Y-%m-%d',errors='coerce')

In [119]:
df_subs[
    ["subscription_id", "account_id", "start_date"]
].isna().sum()

subscription_id    0
account_id         0
start_date         0
dtype: int64

**Support Ticket**

In [120]:
df_sup_ticks=pd.read_csv('ravenstack_support_tickets.csv')

In [121]:
df_sup_ticks.head()

,ticket_id,account_id,submitted_at,closed_at,resolution_time_hours,priority,first_response_time_minutes,satisfaction_score,escalation_flag
0,T-0024de,A-712f1c,2023-07-27,2023-07-28 03:00:00,27.0,high,74,NaN,False
1,T-4d04b9,A-e43bf7,2024-07-08,2024-07-09 03:00:00,27.0,urgent,144,NaN,False
2,T-d5e12f,A-0f3e88,2024-10-17,2024-10-17 19:00:00,19.0,urgent,93,4.0,False
3,T-dfce9a,A-4c56c9,2024-09-08,2024-09-09 23:00:00,47.0,medium,126,5.0,False
4,T-c59f77,A-6f8ad2,2024-11-30,2024-12-01 02:00:00,26.0,medium,8,NaN,False

In [122]:
df_sup_ticks['submitted_at'] = pd.to_datetime(df_sup_ticks['submitted_at'], format='%Y-%m-%d',errors='coerce')
df_sup_ticks['closed_at'] = pd.to_datetime(df_sup_ticks['closed_at'], format='%Y-%m-%d %H:%M:%S',errors='coerce')

# **Created new dataframe**

## 1. Maps account with feature usage

In [123]:
account_feature_usage_df = df_ft_us.merge(
    df_subs[["subscription_id", "account_id"]],
    on="subscription_id",
    how="left"
)

In [124]:
account_feature_usage_df.head()

,usage_id,subscription_id,usage_date,feature_name,usage_count,usage_duration_secs,error_count,is_beta_feature,account_id
0,U-1c6c24,S-0fcf7d,2023-07-27,feature_20,9,5004,0,False,A-e08cd3
1,U-f07cb8,S-c25263,2023-08-07,feature_5,9,369,0,False,A-c7ffc2
2,U-096807,S-f29e7f,2023-12-07,feature_3,9,1458,0,False,A-bbe56f
3,U-6b1580,S-be655e,2024-07-28,feature_40,5,2085,0,False,A-7f29a7
4,U-720a29,S-f9b1d0,2024-12-02,feature_12,12,900,0,False,A-65a46c

In [125]:
df_ft_us[["subscription_id", "usage_date"]].isna().sum()

subscription_id    0
usage_date         0
dtype: int64

## 2. Churn mapped with accounts

In [126]:
account_churn_events_df = (
    df_churn
    .groupby("account_id", as_index=False)
    .agg(churn_date=("churn_date", "min"))
)

In [127]:
account_churn_events_df["churn_event_flag"] = 1

In [128]:
account_churn_events_df

    account_id churn_date  churn_event_flag
0     A-00bed1 2024-01-03                 1
1     A-016043 2024-08-11                 1
2     A-029f69 2024-06-17                 1
3     A-02cd81 2024-04-30                 1
4     A-02fac6 2024-08-21                 1
..         ...        ...               ...
347   A-fd7ad3 2024-11-12                 1
348   A-fda07f 2024-09-13                 1
349   A-ff3c73 2023-12-09                 1
350   A-ffc04f 2024-08-03                 1
351   A-ffdfd5 2024-08-08                 1

[352 rows x 3 columns]

In [129]:
accounts_churn_compare_df = df_acc.merge(
    account_churn_events_df,
    on="account_id",
    how="left"
)

In [130]:
accounts_churn_compare_df["churn_event_flag"] = (
    accounts_churn_compare_df["churn_event_flag"]
    .fillna(0)
    .astype(int)
)

In [131]:
false_positive_churn = accounts_churn_compare_df[
    (accounts_churn_compare_df["churn_flag"] == True) &
    (accounts_churn_compare_df["churn_event_flag"] == 0)
]

false_positive_churn.shape[0]

35

In [132]:
false_negative_churn = accounts_churn_compare_df[
    (accounts_churn_compare_df["churn_flag"] == True) & # Actual churn
    (accounts_churn_compare_df["churn_event_flag"] == 0) # No churn event detected
]

false_negative_churn.shape[0]

35

In [133]:
account_churn_truth_df = account_churn_events_df.copy()

account_churn_truth_df["is_churned"] = 1

In [134]:
accounts_with_churn_df = df_acc.merge(
    account_churn_truth_df[["account_id", "is_churned", "churn_date"]],
    on="account_id",
    how="left"
)

In [135]:
accounts_with_churn_df["is_churned"] = (
    accounts_with_churn_df["is_churned"]
    .fillna(0)
    .astype(int)
)

In [136]:
accounts_with_churn_df["is_churned"].value_counts()

accounts_with_churn_df.loc[
    (accounts_with_churn_df["is_churned"] == 1) &
    (accounts_with_churn_df["churn_date"].isna())
].shape[0]

0

In [137]:
def missing_summary(df, name):
    print(f"\nMissing values in {name}")
    print(df.isna().sum()[df.isna().sum() > 0])

missing_summary(df_acc, "df_acc")
missing_summary(df_subs, "df_subs")
missing_summary(df_ft_us, "df_ft_us")
missing_summary(df_churn, "df_churn")
missing_summary(df_sup_ticks, "df_sup_ticks")

Missing values in df_acc
Series([], dtype: int64)

Missing values in df_subs
end_date    4514
dtype: int64

Missing values in df_ft_us
Series([], dtype: int64)

Missing values in df_churn
feedback_text    148
dtype: int64

Missing values in df_sup_ticks
satisfaction_score    825
dtype: int64

In [138]:
def duplicate_count(df, name):
    print(f"\nDuplicate rows in {name}: {df.duplicated().sum()}")

duplicate_count(df_acc, "df_acc")
duplicate_count(df_subs, "df_subs")
duplicate_count(df_ft_us, "df_ft_us")
duplicate_count(df_churn, "df_churn")
duplicate_count(df_sup_ticks, "df_sup_ticks")

Duplicate rows in df_acc: 0

Duplicate rows in df_subs: 0

Duplicate rows in df_ft_us: 0

Duplicate rows in df_churn: 0

Duplicate rows in df_sup_ticks: 0

# **PHASE - 2 : **USER** BEHAVIOUR AND ENGAGEMENT ANALYSIS**

In [139]:
account_feature_usage_df.head()

,usage_id,subscription_id,usage_date,feature_name,usage_count,usage_duration_secs,error_count,is_beta_feature,account_id
0,U-1c6c24,S-0fcf7d,2023-07-27,feature_20,9,5004,0,False,A-e08cd3
1,U-f07cb8,S-c25263,2023-08-07,feature_5,9,369,0,False,A-c7ffc2
2,U-096807,S-f29e7f,2023-12-07,feature_3,9,1458,0,False,A-bbe56f
3,U-6b1580,S-be655e,2024-07-28,feature_40,5,2085,0,False,A-7f29a7
4,U-720a29,S-f9b1d0,2024-12-02,feature_12,12,900,0,False,A-65a46c

## **Usage Metrics**

In [140]:
account_engagement_df = (
    account_feature_usage_df
    .groupby("account_id")
    .agg(
        total_events=("usage_date", "count"),
        active_days=("usage_date", "nunique"),
        first_usage_date=("usage_date", "min"),
        last_usage_date=("usage_date", "max")
    )
    .reset_index()
)

In [141]:
analysis_date = account_feature_usage_df["usage_date"].max()

account_engagement_df["days_since_last_use"] = (
    analysis_date - account_engagement_df["last_usage_date"]
).dt.days

In [142]:
account_engagement_df = account_engagement_df.merge(
    accounts_with_churn_df[["account_id", "is_churned", "churn_date"]],
    on="account_id",
    how="left"
)

In [143]:
account_engagement_df["total_events"] = account_engagement_df["total_events"].fillna(0)
account_engagement_df["active_days"] = account_engagement_df["active_days"].fillna(0)

In [144]:
account_engagement_df.head(5)

,account_id,total_events,active_days,first_usage_date,last_usage_date,days_since_last_use,is_churned,churn_date
0,A-00bed1,51,49,2023-01-07,2024-12-14,17,1,2024-01-03
1,A-00cac8,58,57,2023-01-01,2024-12-24,7,0,NaT
2,A-0158bb,36,35,2023-01-11,2024-12-28,3,0,NaT
3,A-016043,47,46,2023-02-16,2024-12-31,0,1,2024-08-11
4,A-019782,55,55,2023-01-08,2024-12-20,11,0,NaT

# **PHASE - 3 : COHORT & RETENTION ANALYSIS**

In [145]:
df_acc["signup_month"] = (
    df_acc["signup_date"]
    .dt.to_period("M")
    .astype(str)
)

In [146]:
account_feature_usage_df["activity_month"] = (
    account_feature_usage_df["usage_date"]
    .dt.to_period("M")
    .astype(str)
)

In [147]:
usage_with_cohort_df = account_feature_usage_df.merge(
    df_acc[["account_id", "signup_month"]],
    on="account_id",
    how="left"
)

In [148]:
usage_with_cohort_df["signup_month"] = pd.PeriodIndex(
    usage_with_cohort_df["signup_month"], freq="M"
)

usage_with_cohort_df["activity_month"] = pd.PeriodIndex(
    usage_with_cohort_df["activity_month"], freq="M"
)

In [149]:
usage_with_cohort_df["month_offset"] = (
    usage_with_cohort_df["activity_month"] -
    usage_with_cohort_df["signup_month"]
).apply(lambda x: x.n)

usage_with_cohort_df = usage_with_cohort_df[
    usage_with_cohort_df["month_offset"] >= 0
]

In [150]:
cohort_activity_df = (
    usage_with_cohort_df
    .groupby(["signup_month", "month_offset"])["account_id"]
    .nunique()
    .reset_index(name="active_accounts")
)

In [151]:
cohort_activity_df

    signup_month  month_offset  active_accounts
0        2023-01             0               16
1        2023-01             1               12
2        2023-01             2               15
3        2023-01             3               16
4        2023-01             4               16
..           ...           ...              ...
295      2024-10             1               23
296      2024-10             2               26
297      2024-11             0               29
298      2024-11             1               25
299      2024-12             0               13

[300 rows x 3 columns]

In [152]:
cohort_size_df = (
    df_acc
    .groupby("signup_month")["account_id"]
    .nunique()
    .reset_index(name="cohort_size")
)

In [153]:
cohort_size_df["signup_month"] = pd.PeriodIndex(cohort_size_df["signup_month"], freq="M")

cohort_retention_df = cohort_activity_df.merge(
    cohort_size_df,
    on="signup_month",
    how="left"
)

In [154]:
cohort_retention_df["retention_rate"] = (
    cohort_retention_df["active_accounts"] /
    cohort_retention_df["cohort_size"]
)

# **PHASE 4 : CHURN DRIVER ANALYSIS**

In [155]:
churned_df = account_engagement_df[account_engagement_df["is_churned"] == 1]
active_df = account_engagement_df[account_engagement_df["is_churned"] == 0]

In [156]:
usage_compare = account_engagement_df.groupby("is_churned")[[
    "total_events",
    "active_days",
    "days_since_last_use"
]].describe()

usage_compare

           total_events                                                        \
                  count       mean        std   min    25%   50%   75%    max
is_churned
0                 148.0  49.391892  15.969203  12.0  36.75  49.0  61.0   91.0
1                 352.0  50.255682  17.691966  10.0  38.00  50.0  62.0  101.0

           active_days             ...             days_since_last_use  \
                 count       mean  ...   75%   max               count
is_churned                         ...
0                148.0  47.689189  ...  58.0  87.0               148.0
1                352.0  48.446023  ...  60.0  96.0               352.0


                 mean        std  min  25%   50%   75%    max
is_churned
0           16.756757  17.843470  0.0  4.0  11.0  23.0   99.0
1           16.125000  18.026769  0.0  4.0  11.0  21.0  136.0

[2 rows x 24 columns]

In [157]:
churned_df = churned_df.merge(
    df_acc[["account_id", "signup_date"]],
    on="account_id",
    how="left"
)

churned_df["tenure_days"] = (
    churned_df["churn_date"] - churned_df["signup_date"]
).dt.days

In [158]:
churned_df["tenure_days"].describe()

count    352.000000
mean     133.051136
std      138.869685
min        0.000000
25%       27.750000
50%       81.500000
75%      198.750000
max      608.000000
Name: tenure_days, dtype: float64

In [159]:
EARLY_CHURN_DAYS = 30

churned_df["churn_type"] = churned_df["tenure_days"].apply(
    lambda x: "early" if x <= EARLY_CHURN_DAYS else "late"
)

churned_df["churn_type"].value_counts()

churn_type
late     261
early     91
Name: count, dtype: int64

In [160]:
account_plan_df = df_subs[[
    "account_id",
    "plan_tier"
]].drop_duplicates()

In [161]:
plan_churn_df = accounts_with_churn_df.merge(
    account_plan_df,
    on="account_id",
    how="left"
)
plan_churn_df["plan_tier"] = plan_churn_df["plan_tier_y"]

In [162]:
plan_churn_summary = plan_churn_df.groupby("plan_tier")["is_churned"].mean()

plan_churn_summary

plan_tier
Basic         0.704167
Enterprise    0.703549
Pro           0.700422
Name: is_churned, dtype: float64

In [163]:
df_subs

,subscription_id,account_id,start_date,end_date,plan_tier,seats,mrr_amount,arr_amount,is_trial,upgrade_flag,downgrade_flag,churn_flag,billing_frequency,auto_renew_flag
0,S-8cec59,A-3c1a3f,2023-12-23,2024-04-12,Enterprise,14,2786,33432,False,False,False,True,monthly,True
1,S-0f6f44,A-9b9fe9,2024-06-11,NaT,Pro,17,833,9996,False,False,False,False,monthly,True
2,S-51c0d1,A-659280,2024-11-25,NaT,Enterprise,62,0,0,True,True,False,False,annual,False
3,S-f81687,A-e7a1e2,2024-11-23,2024-12-13,Enterprise,5,995,11940,False,False,False,True,monthly,True
4,S-cff5a2,A-ba6516,2024-01-10,NaT,Enterprise,27,5373,64476,False,False,False,False,monthly,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,S-c158df,A-fa2041,2024-10-27,NaT,Enterprise,18,3582,42984,False,False,False,False,monthly,True
4996,S-b49c0a,A-db5e9e,2024-12-05,NaT,Pro,23,1127,13524,False,False,False,False,monthly,False
4997,S-42822d,A-443f6f,2024-12-15,NaT,Pro,25,1225,14700,False,False,False,False,annual,True
4998,S-432401,A-c7ffc2,2023-05-25,NaT,Pro,132,6468,77616,False,False,False,False,monthly,True
4999,S-71fc3d,A-ccb686,2024-12-06,NaT,Enterprise,10,1990,23880,False,False,False,False,monthly,True

In [164]:
df_sup_ticks['resolution_time'] = (df_sup_ticks['closed_at'] - df_sup_ticks['submitted_at']).dt.total_seconds() / (60*60*24) # in days

support_agg_df = (
    df_sup_ticks
    .groupby("account_id")
    .agg(
        ticket_count=("ticket_id", "count"),
        avg_resolution_time=("resolution_time", "mean")
    )
    .reset_index()
)

In [165]:
account_churn_support_df = account_engagement_df.merge(
    support_agg_df,
    on="account_id",
    how="left"
)

In [166]:
account_churn_support_df[["ticket_count", "avg_resolution_time"]] = (
    account_churn_support_df[["ticket_count", "avg_resolution_time"]]
    .fillna(0)
)

In [167]:
support_compare = account_churn_support_df.groupby("is_churned")[[
    "ticket_count",
    "avg_resolution_time"
]].describe()

support_compare

           ticket_count                                               \
                  count      mean      std  min  25%  50%  75%   max
is_churned
0                 148.0  4.087838  2.06338  0.0  3.0  4.0  5.0   9.0
1                 352.0  3.963068  1.81833  0.0  3.0  4.0  5.0  11.0

           avg_resolution_time                                               \
                         count      mean       std  min       25%       50%
is_churned
0                        148.0  1.479668  0.530164  0.0  1.201786  1.500000
1                        352.0  1.488349  0.522384  0.0  1.190625  1.475694


                 75%  max
is_churned
0           1.758854  3.0
1           1.791667  3.0

In [168]:
churn_driver_summary = account_churn_support_df.groupby("is_churned").agg(
    avg_events=("total_events", "mean"),
    avg_active_days=("active_days", "mean"),
    avg_days_since_last_use=("days_since_last_use", "mean"),
    avg_ticket_count=("ticket_count", "mean"),
    avg_resolution_time=("avg_resolution_time", "mean")
)

churn_driver_summary

,avg_events,avg_active_days,avg_days_since_last_use,avg_ticket_count,avg_resolution_time
is_churned,,,,,
0,49.391892,47.689189,16.756757,4.087838,1.479668
1,50.255682,48.446023,16.125000,3.963068,1.488349

# **PHASE 5 : REVENUE & BUSINESS IMPACT**

In [169]:
account_revenue_df = (
    df_subs
    .sort_values("mrr_amount", ascending=False)
    .drop_duplicates(subset=["account_id"])
    [["account_id", "mrr_amount", "arr_amount"]]
)

In [170]:
revenue_churn_df = accounts_with_churn_df.merge(
    account_plan_df,
    on="account_id",
    how="left"
).merge(
    account_revenue_df,
    on="account_id",
    how="left"
)

revenue_churn_df["plan_tier"] = revenue_churn_df["plan_tier_y"]

In [171]:
revenue_churn_df[["mrr_amount", "arr_amount"]] = (
    revenue_churn_df[["mrr_amount", "arr_amount"]].fillna(0)
)

In [172]:
total_mrr = revenue_churn_df["mrr_amount"].sum()
active_mrr = revenue_churn_df.loc[
    revenue_churn_df["is_churned"] == 0, "mrr_amount"
].sum()
churned_mrr = revenue_churn_df.loc[
    revenue_churn_df["is_churned"] == 1, "mrr_amount"
].sum()

In [173]:
total_mrr = revenue_churn_df["mrr_amount"].sum()
active_mrr = revenue_churn_df.loc[
    revenue_churn_df["is_churned"] == 0, "mrr_amount"
].sum()
churned_mrr = revenue_churn_df.loc[
    revenue_churn_df["is_churned"] == 1, "mrr_amount"
].sum()

In [174]:
logo_churn_rate = revenue_churn_df["is_churned"].mean()
revenue_churn_rate = churned_mrr / total_mrr if total_mrr > 0 else 0

In [175]:
revenue_churn_by_plan = (
    revenue_churn_df
    .groupby("plan_tier")
    .agg(
        total_mrr=("mrr_amount", "sum"),
        churned_mrr=("mrr_amount", lambda x: x[revenue_churn_df.loc[x.index, "is_churned"] == 1].sum()),
        churned_accounts=("is_churned", "sum"),
        total_accounts=("account_id", "count")
    )
    .reset_index()
)

revenue_churn_by_plan["revenue_churn_rate"] = (
    revenue_churn_by_plan["churned_mrr"] / revenue_churn_by_plan["total_mrr"]
).fillna(0)

In [176]:
print(f"Total MRR: {total_mrr:,.0f}")
print(f"Active MRR: {active_mrr:,.0f}")
print(f"Churned MRR: {churned_mrr:,.0f}")
print(f"Logo Churn Rate: {logo_churn_rate:.2%}")
print(f"Revenue Churn Rate: {revenue_churn_rate:.2%}")
revenue_churn_by_plan

Total MRR: 11,170,422
Active MRR: 3,297,046
Churned MRR: 7,873,376
Logo Churn Rate: 70.27%
Revenue Churn Rate: 70.48%

,plan_tier,total_mrr,churned_mrr,churned_accounts,total_accounts,revenue_churn_rate
0,Basic,3668448,2575001,338,480,0.701932
1,Enterprise,3807859,2694337,337,479,0.707573
2,Pro,3694115,2604038,332,474,0.704915

In [177]:
retention_matrix = cohort_retention_df.pivot_table(
    index="signup_month",
    columns="month_offset",
    values="retention_rate"
)

# **PHASE 6 : INSIGHTS SYNTHESIS**

In [178]:
engagement_summary = (
    account_engagement_df
    .groupby("is_churned")
    .agg(
        avg_events=("total_events", "mean"),
        avg_active_days=("active_days", "mean"),
        avg_days_since_last_use=("days_since_last_use", "mean")
    )
    .reset_index()
)

In [179]:
support_summary = (
    df_sup_ticks
    .groupby("account_id")
    .agg(
        ticket_count=("ticket_id", "count"),
        avg_resolution_time=("resolution_time", "mean")
    )
    .reset_index()
)

In [180]:
support_churn_summary = (
    revenue_churn_df
    .merge(support_summary, on="account_id", how="left")
    .fillna(0)
    .groupby("is_churned")
    .agg(
        avg_ticket_count=("ticket_count", "mean"),
        avg_resolution_time=("avg_resolution_time", "mean")
    )
    .reset_index()
)

In [181]:
insights_df = pd.DataFrame({
    "insight_id": [1, 2, 3, 4],
    "insight": [
        "Churned accounts have significantly lower engagement",
        "Churn mostly happens early in the customer lifecycle",
        "Revenue churn is concentrated in specific plan tiers",
        "Accounts with more support tickets churn more often"
    ],
    "primary_metric": [
        "total_events / active_days",
        "tenure_days",
        "revenue_churn_rate",
        "ticket_count"
    ]
})

# **PHASE 7 : DECISIONS AND EXPERIMENTATIONS**

In [182]:
decisions_df = pd.DataFrame({
    "decision_id": [1, 2, 3, 4],
    "related_insight": [1, 2, 3, 4],
    "decision": [
        "Improve onboarding to drive early engagement",
        "Introduce early lifecycle intervention",
        "Re-evaluate pricing / value for high-churn plans",
        "Improve support response time and issue resolution"
    ],
    "expected_metric_impact": [
        "Increase activation & reduce early churn",
        "Reduce churn in first 30 days",
        "Reduce revenue churn",
        "Reduce churn linked to support friction"
    ]
})

In [183]:
experiments_df = pd.DataFrame({
    "experiment_id": [1, 2, 3],
    "hypothesis": [
        "Improved onboarding will increase 30-day retention",
        "Early lifecycle nudges will reduce early churn",
        "Faster support resolution reduces churn"
    ],
    "primary_metric": [
        "30_day_retention",
        "early_churn_rate",
        "churn_rate"
    ],
    "success_criteria": [
        "+5% retention lift",
        "-5% early churn",
        "-3% churn"
    ]
})

# **Created : Account Engagement Summary**

In [184]:
analysis_date = account_feature_usage_df["usage_date"].max()

account_engagement_summary = (
    account_feature_usage_df
    .groupby("account_id")
    .agg(
        total_events=("usage_date", "count"),
        active_days=("usage_date", "nunique"),
        first_usage_date=("usage_date", "min"),
        last_usage_date=("usage_date", "max")
    )
    .reset_index()
)

account_engagement_summary["days_since_last_use"] = (
    analysis_date - account_engagement_summary["last_usage_date"]
).dt.days

account_engagement_summary = account_engagement_summary.merge(
    accounts_with_churn_df[["account_id", "is_churned"]],
    on="account_id",
    how="left"
)

account_engagement_summary["account_id"].is_unique

True

# **BI HANDOFF : POWER BI / DASHBOARD EXPORT**

In [185]:
account_engagement_df.to_csv("bi_account_engagement.csv", index=False)
retention_matrix.reset_index().to_csv("bi_retention_matrix.csv", index=False)
revenue_churn_df.to_csv("bi_revenue_churn.csv", index=False)
revenue_churn_by_plan.to_csv("bi_revenue_churn_by_plan.csv", index=False)
insights_df.to_csv("bi_insights.csv", index=False)
decisions_df.to_csv("bi_decisions.csv", index=False)
experiments_df.to_csv("bi_experiments.csv", index=False)
account_engagement_summary.to_csv(
    "bi_account_engagement_summary.csv",
    index=False
)

print("BI EXPORT COMPLETE")

BI EXPORT COMPLETE